### ISSUE TITLE
Localcopy not working in latest Jabref beta version (11b4)

### ISSUE THREAD

**Issue by minkkinen** [lehner/LocalCopy#6]
I cannot get Localcopy to work in the most recent beta version of Jabref (11b4). Here's the error console output:

Exception in thread "main" java.lang.NoSuchMethodError: localcopy.LocalCopySidePaneComponent.setContent(Ljava/awt/Component;)V
    at localcopy.LocalCopySidePaneComponent.<init>(LocalCopyPane.java:219)
    at localcopy.LocalCopyPane.getSidePaneComponent(LocalCopyPane.java:578)
    at net.sf.jabref.JabRef.startSidePanePlugins(Unknown Source)
    at net.sf.jabref.JabRef.openWindow(Unknown Source)
    at net.sf.jabref.JabRef.start(Unknown Source)
    at net.sf.jabref.JabRefMain.main(Unknown Source)

I wonder if there is some easy solution?

**Comment by minkkinen** [comment]
My bad. Plugins are no longer supported in the latest versions. Here is a discussion about a native replacement for the plugin: https://github.com/JabRef/jabref/pull/101
