### ISSUE TITLE
Exception after clicking "journal PDF" in JabRef 2.10

### ISSUE THREAD

**Issue by nemobis** [lehner/LocalCopy#8]
I'm using LocalCopy 2.6 with JabRef 2.10. I imported a bibtex files with some DOIs and I clicked "journal PDF" after selecting one of them. The dialog hangs forever and I see:

```
LocalCopy: updated to version 1.5
Exception in thread "Thread-6" java.lang.NoSuchMethodError: net.sf.jabref.labelPattern.LabelPatternUtil.makeLabel(Lnet/sf/jabref/labelPattern/LabelPattern;Lnet/sf/jabref/BibtexDatabase;Lnet/sf/jabref/BibtexEntry;)Lnet/sf/jabref/BibtexEntry;
        at localcopy.FNTemplate.getKey(FNTemplate.java:58)
        at localcopy.FNTemplate.getFN(FNTemplate.java:100)
        at localcopy.Download.downloadFromPage(Download.java:558)
        at localcopy.CommandDoiUrl.run(LocalCopyPane.java:139)
        at localcopy.ProgressDialog$Task.run(ProgressDialog.java:118)
```

I can't tell whether this is the same as some other reports here; the versions seem different.

**Comment by Siedlerchr** [comment]
I am just curious, do you know that JabRef has several full text fetchers integrated since Version 3?
You could check out the version 4. As 2.10 is a very very old version

**Comment by nemobis** [comment]
Thanks for your question: no, I did not know. I'm new to JabRef, I just found http://www.lhnr.de/ext/localcopy/ because it was one of the top ~20 results for "DOI PDF download" or a similar search.

2.10 is just what I found in the fedora repositories for a quick test, I'll try a more recent version as you suggested.

**Comment by nemobis** [comment]
Ok, found: https://help.jabref.org/en/#-using-online-bibliographic-database
Not quite what I had in mind, but seems to serve a portion of my needs. If this plugin was supposed to have the same scope and the exception is not relevant, feel free to close. :-)

**Comment by tobiasdiez** [comment]
In the new 4.0 version, you have a download button next to the DOI field that lets you fetch fulltext files (similar for other identifiers, e.g arXiv id).

**Comment by nemobis** [comment]
I cannot test 4, it seems to require Oracle Java per https://help.jabref.org/en/Installation . 3.8.2 fetches some stuff from IOP, Springer an arXiv but seems to fail anything else.

**Comment by Siedlerchr** [comment]
@nemobis  Openjdk 8  + openjfx should also work:
https://fedoraproject.org/wiki/Java

**Comment by nemobis** [comment]
Christoph, 11/10/2017 16:32:
> @nemobis <https://github.com/nemobis> Openjdk 8 + openjfx should also work:
> https://fedoraproject.org/wiki/Java

Nope, it doesn't for me, but I'll report that separately.
